name: Remove old artifacts

on:  
  push:
    branches: 
    - staging
  pull_request:
    branches: 
    - staging
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'
  
  uses: actions/github-script@v6
  id: artifact
  with:
    script: |
      const res = await github.rest.actions.listArtifactsForRepo({
        owner: context.repo.owner,
        repo: context.repo.repo,
      })

      res.data.artifacts
        .forEach(({ id }) => {
          github.rest.actions.deleteArtifact({
            owner: context.repo.owner,
            repo: context.repo.repo,
            artifact_id: id,
          })
        })