name: PMD Security Analysis

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

permissions:
  contents: read
  security-events: write

jobs:
  pmd:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - uses: pmd/pmd-github-action@v1
        with:
          version: '7.0.0-rc4'
          sourcePath: 'src/main/java'
          rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'
          analyzeModifiedFilesOnly: false
          format: 'sarif'
          outputFile: 'pmd-report.sarif'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'pmd-report.sarif'
